### ISSUE TITLE
How to make it work with async functions or Promises?

### ISSUE THREAD

**Issue by matronator** [lau1944/bunrest#13]
I am using [great.db](https://github.com/tr1ckydev/great.db) as my database and all their functions return Promises. When I try to return some data from the database that got returned via a Promise, I get this message: `Welcome to Bun! To get started, return a Response object.`

I tried both async and Promises, here's the code:

```
// with Promises
router.get('/projects', (req, res) => {
    const data = Table.project.get('id', undefined, true).then(() => {
        res.status(200).json(data);
    });
});

// using async
router.get('/projects', async (req, res) => {
    const data = await Table.project.get('id', undefined, true);
    res.status(200).json(data);
});
```

Neither seems to return anything except the message mentioned earlier. How do I make this work with async fetching from database?

**Comment by lau1944** [comment]
@matronator I can reproduce your issue now, I will look into it.

**Comment by lau1944** [comment]
@matronator fixed

**Comment by matronator** [comment]
That was fast, thank you! When can I expect it in a release on npm?
