### ISSUE TITLE
Sessions?

### ISSUE THREAD

**Issue by joshholly** [lau1944/bunrest#25]
I am trying to convert my app from express to bunrest. Right now, I use express-session for my sessions. But when I do req.session it says session isn't apart of bunret. So How do I handle sessions?

**Comment by lau1944** [comment]
`bunrest-1.3.4`

Do the same thing like in express

```js
npm install express-session cookie-parser
```

```js
import Server from "bunrest";

const app = Server()
const session = require("express-session");
const cookieParser = require("cookie-parser");

server.use(cookieParser());
 // sample code
server.use(session({
    secret: "amar",
    saveUninitialized: true,
    resave: true
}));
```

Then you can use it like
```js
app.get('/', (req, res) => {
  req.session
})
```

**Comment by joshholly** [comment]
Is it possible to use it in a non-typescript setting? Right now, with
express, I do it like:

const express = require("express");
const app = express();

Right now, my site isn't in typescript, and it would take me forever to
convert my site from regular JS to typescript. But I'd like to switch over
to a more bun-friendly js.
