### ISSUE TITLE
For beginners, may want to include the `app.listen` code snippet in the `README.md`

### ISSUE THREAD

**Issue by dainank** [lau1944/bunrest#26]
Novices may read the `README.md` and struggle to understand how to actually keep the server alive. Including the code snippet in the `README.md` may be useful for such beginners:

```ts
server.listen(3000, () => {
  console.log('App is listening on port 3000: http://localhost:3000');
});
```

**Comment by lau1944** [comment]
`listen` should be used after adding request handler.
