### ISSUE TITLE
Cant get custom response

### ISSUE THREAD

**Issue by craftzneko** [lau1944/bunrest#38]
New to this so probably missed something really obvious, no matter what i do i cant seem to get a custom response back when pusing put

```javascript
app.put('/api/data', async (req, res) => {
  const { ComputerName, AgentVer, DateScanned, SummaryJSON } = req.body;

  // write a query to insert the data into the database
  const query = {
    text: 'INSERT INTO ICTSignal(ComputerName, AgentVer, DateCreated, SummaryJSON) VALUES($1, $2, $3, $4)',
    values: [ComputerName, AgentVer, DateScanned, JSON.stringify(SummaryJSON)],
  };

  // execute the query
  await client.query(query, (err) => {
    if (err) {
      console.log(err.stack);
      res.status(500).json({ message: 'Error in database operation' });
    } else {console.log(res.status)
      res.status(200).json({ message: 'Data inserted successfully' });
    }
  });
});
```

![image](https://github.com/lau1944/bunrest/assets/662108/04fbc26b-c4cd-46f1-b6f0-239b9f3303b6)

what am i doing wrong here

**Comment by MikkelSVDK** [comment]
Isn't it just because `await client.query(query, (err) => {})` err is only runs if there is an error with the query?
Since you use `await client.query()` can't you change that to `const { data, err } = await client.query(query)` and make a early return if err is set? Idk what package `client` is, so im just assuming that it returns some object.

**Comment by craftzneko** [comment]
@MikkelSVDK the callback function should run when the query is complete. if an error is there it follows that logic otherwise drops to else statement. I actually couldn't get it to work, so switched to using express. I am sure it was my issue somewhere just could never find what i was missing
