### ISSUE TITLE
Can't Have Hyphenated Route Names

### ISSUE THREAD

**Issue by davidn000** [lau1944/bunrest#6]
I am running BunRest on Bun v0.1.13, and there seems to be an issue with the route names containing hyphens. All routes paths that start with the word before the hyphen and onwards on the hyphenated route will resolve to the hyphenated endpoint. Ex. if the '/api' route is requested, "hello world" with a status of 200 will be the response. The same for '```/api-```', '```/api-e```', '```/api-en...```', and '```/api-endpoint-any-other-text-after_doesntneedtobehyphenated```'.

Code to reproduce this error:
```javascript
import server from "bunrest";

const app = server();
app.get('/api-endpoint', (request, response) => {
    response.status(200).json({message:"hello world!"});
});
app.get('/api', (request, response) => {
    response.status(500).json({message: "error!"});
});

app.listen(4000, () => {
    console.log('App is listening on port 3000');
});
```

console output:
```bash
[davidn000@linux]$ bun buntest.js 
App is listening on port 3000 
```

**Comment by davidn000** [comment]
Forked and fixed. Created a pull request for you approval. [https://github.com/lau1944/bunrest/pull/7](https://github.com/lau1944/bunrest/pull/7)

**Comment by lau1944** [comment]
@davidn000 check out #7 and [v1.1.5](https://www.npmjs.com/package/bunrest)
