### ISSUE TITLE
bug .env files

### ISSUE THREAD

**Issue by i-Lucas** [lau1944/bunrest#8]
I think the server is starting before completely reading the .env file and it crashes

https://i.imgur.com/ZI2mryi.png

**Comment by lau1944** [comment]
Step for using `dotenv`

1. bun install [dotenv](https://www.npmjs.com/package/dotenv)
2. read dotenv module
```js
import * as dotenv from 'dotenv' 
dotenv.config()
```
3. Then you can use `process.env.xx`

It works for me.

**Comment by i-Lucas** [comment]
https://i.imgur.com/C5lDZEM.png


here the problem continues.
noticed it happens when nodemon reloads

**Comment by i-Lucas** [comment]
https://i.imgur.com/MzoZCXy.png


**correction**

it doesn't just happen with nodemon.
start command also had this problem

**Comment by lau1944** [comment]
I cannot reproduce the issue, it works fine for me even without the `dotenv` imported. 
Can u upload your sample code and steps to run the program?

**Comment by i-Lucas** [comment]
sure, here is the link
https://github.com/i-Lucas/code-inssue-bug-.env-bunrest

you can reproduce the problem if you run npm start repeatedly.

example:

npm start , ctrl + c npm start again...
randomly the problem happens

the big issue is that this also occurs when uploading the container, so there is a chance it might break in production and need to restart manually

**Comment by i-Lucas** [comment]
another detail: when the execution doesn't give a problem and the server goes up using the port of the .env file, it's impossible to make requests to the server.

the error sent is: Connection was forcibly closed by a peer.
using fixed port at 5000 the server is able to receive requests normally
my operating system is ubuntu 22.04lts

**Comment by lau1944** [comment]
I ran the program, it looks fine. Maybe try to use `bun start` to run the program?
If the issue still occurs, I don't think it's related to this library, `bunrest` is just a wrapper or a handler for bun, you might need to create an issue on `bun` repo.
