### ISSUE TITLE
Raw request body?

### ISSUE THREAD

**Issue by mmcc** [lau1944/bunrest#9]
Hi there, I was playing around with bunrest a bit for a weekend project and I've found myself in a situation where I need to access the raw request body. I'm not seeing anything immediately obvious in the docs, and trying to access things via `req.request.body` eventually end up with an error that `Body is already used`.

Any ideas?

**Comment by lau1944** [comment]
`req.request` is a bun request object, there is no `body` variable.
You can try `req.body` instead.
